name: AzuraChat
version: '${version}'
main: cc.azuramc.azurachat.AzuraChat
api-version: '1.13'
authors: [an5w1r@163.com]
description: A customizable chat plugin with PlaceholderAPI support
website: https://azuramc.cc
softdepend: [PlaceholderAPI]
folia-supported: true

commands:
  azurachat:
    description: AzuraChat main command
    usage: /azurachat <reload>
    permission: azurachat.admin

permissions:
  azurachat.reload:
    description: Reload plugin configuration
    default: op
